### ISSUE TITLE
UI sometimes stale with zome function calls are running for a long time

### ISSUE THREAD

**Issue by lucksus** [kristoferlund/holotxt#3]
The UI didn't refresh to show my old notes nor updated contents of a note I've open via address. I've opened the Holoscape debug view to see what's going on. I could find the note entry in the DHT section and I could also see the running zome function call.

When I wait for many seconds (minutes?) the function returns and the UI shows updated content.

Without looking into code, my guess is that you're using `hdk::send()` somehow for the real-time collaboration but without overriding the default timeout. `hdk::send()` blocks until it gets a response or the timeout get's triggered. If it used for real-time communication between nodes, the timeout should be set to a very low value to have it return immediately since the other party could either be offline in general or not reachable temporarily.

This is just a guess, but we had the exact same problem in basic chat at some point :)

**Comment by kristoferlund** [comment]
You are probably correct, I will investigate as soon as I find time, thanks for spotting!

**Comment by kristoferlund** [comment]
The issue you had probably didn't have to do with the `hdk::send()` function but with `hdk::api::get_links()` causing timeout issues. Issue should be fixed by now. I'll wait until next version of holoscape and post an update to the appstore then. 

But, on the topic of the send function. I'm having troubles with that timeout as well. 

```rust
hdk::api::send(agent_address, payload, 2000.into())
```
Above call still takes a minute or so to timeout if other agent is offline. Am I missing something?

**Comment by kristoferlund** [comment]
I've added some additional error handling, switched to a more reliable editor component, etc - hopefully correction the issues you are describing. The current version should run much more stable. I will close this issue for now, please post again if you notice other things not working.
